### ISSUE TITLE
Issues with duplicate column names

### ISSUE THREAD

**Issue by camrinbraun** [rmendels/rerddapXtracto#10] opened 2018-12-07 23:28 UTC
I'm getting an error when accessing a different dataset than the rxtracto_3D example in the vignette. It looks like something about this dataset yields duplicated column names that one of the tidyverse packages under the hood doesn't like. MWE and output below:
```{r}
info <- rerddap::info('ncdcOwMon_LonPM180')
```
_<ERDDAP info> ncdcOwMon_LonPM180 
 Dimensions (range):  
     time: (1987-07-15T00:00:00Z, 2011-09-15T00:00:00Z) 
     altitude: (10.0, 10.0) 
     latitude: (-89.75, 89.75) 
     longitude: (-180.0, 179.75) 
 Variables:  
     u: 
         Units: m s-1 
     v: 
         Units: m s-1 
     w: 
         Units: m s-1_ 

``` {r}
extract <- rerddapXtracto::rxtracto_3D(info, parameter='w', xcoord=c(10, 20),
                                       ycoord=c(10, 20), 
                                       tcoord = c(as.Date('2010-01-01'),as.Date('2010-01-01')), 
                                       zcoord = 10, zName = 'altitude', verbose=T)
```
_Error: (converted from warning) Duplicated column names deduplicated: 'Arial' => 'Arial_1' [4], 'Arial' => 'Arial_2' [6], 'Arial' => 'Arial_3' [8], 'Arial' => 'Arial_4' [10], 'Arial' => 'Arial_5' [12]_

**Comment by rmendels** [comment] 2018-12-08 01:07
Hi Camrin:

Thanks for the heads up.  The problem you are seeing is the ERDDAP server is throwing an error.  That is a dataset we serve remotely,  and the remote dataset has become unavailable, which unfortunately happens too often with that agency.  To see this go to:

https://upwell.pfeg.noaa.gov/erddap/griddap/ncdcOwMon_LonPM180.html  

Select only time,  leave the default .htmlTable,  and hit submit,  and ERDDAP throws an error.  That dataset is actually picking it up from coastwatch.pfeg.noaa.gov/erddap,  which is not showing the dataset you are after,  which is how I know it has gone unavailable.  The reddap::info call works because that data is cached.  The aggregate server only updates its information every so often,  and hasn't updated that dataset  (to not show it) yet.

I need to do a better job of sorting out the types of errors, and returning the more informative errors information.  It is on my todo list,  but for now the problem is the dataset is unavailable.

-Roy

**Comment by rmendels** [comment] 2018-12-08 03:53
@camrinbraun - sorry I am bad at Github  Forgot to @ you in my reply.  See the issue page for my answer  (tl;dr - dataset not available).  Okay if I close this issue?

**Comment by camrinbraun** [comment] 2018-12-10 16:51
Yeah, thanks for the info. Agreed that a more informative error would be nice to reduce submitted issues like this one. Go ahead and close it. Thanks!

**Closed as completed** 2018-12-10 16:53 UTC
